"""Added request log model

Revision ID: 7e59b398e829
Revises: c284416d2979
Create Date: 2026-03-24 12:21:12.193095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e59b398e829'
down_revision: Union[str, Sequence[str], None] = 'c284416d2979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('embedding_projections_news_digest_unique'), 'embedding_projections', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('embedding_projections_news_digest_unique'), 'embedding_projections', ['news_id', 'digest_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
